- hosts: all
  become: yes
  gather_facts: no
  vars:
    k8s_version: "1.19.1-0.x86_64"

  tasks:
  - name: check if kubelet is installed
    yum:
      list=kubelet-{{ k8s_version }}
    register: pkg

  - name: all packages are updated
    yum:
      name: '*'
      state: latest

  - name: docker-ce repo is present
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: docker-ce is installed
    yum:
      name: docker-ce
      state: present

  - name: docker is started and enabled
    service:
      name: docker
      state: started
      enabled: yes

  - name: kubernetes repository is present
    yum_repository:
      name: kubernetes
      description: Kubernetes repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      enabled: yes
      gpgcheck: yes
      state: present

  - name: kubelet is installed
    yum:
      name: kubelet-{{ k8s_version }}
      state: present

  - name: kubeadm is installed
    yum:
      name: kubeadm-{{ k8s_version }}
      state: present

  - shell: kubelet --version

- hosts: masters
  become: yes
  gather_facts: no
  vars:
    k8s_version: "1.19.1-0.x86_64"

  tasks:
   - name: kubectl is present
     yum:
        name: kubectl-{{ k8s_version }}
        state: present
