- hosts: masters
  become: yes
  gather_facts: no

  tasks:
    - name: cluster is initialized
      shell: kubeadm init --apiserver-advertise-address=192.168.58.102

    - name: kubelet is started and enabled
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: ansible_tmp dir is created
      become: yes
      become_user: celeguim
      file:
        path: /home/celeguim/.ansible/tmp
        state: directory
        mode: 0755

    - name: create .kube directory
      become: yes
      become_user: celeguim
      file:
        path: /home/celeguim/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/celeguim/.kube/config
        remote_src: yes
        owner: celeguim

    - name: pod network is installed
      become: yes
      become_user: celeguim
      # shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: join command is created
      command: kubeadm token create --print-join-command
      register: join_command

    - name: join command is copied to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      become: false

    - debug: msg = "{{ join_command.stdout_lines[0] }}"
